### ISSUE TITLE
Consider using giscus

### ISSUE THREAD

**Issue by laymonage** [bjcarlson42/benjamincarlson.io#27]
Hey there,

I see that you're using utterances for comments. As we know, it utilizes GitHub Issues, which (given enough time) would flood your repository's issues with comments.

I've been developing an alternative: [giscus](https://giscus.vercel.app), a similar project that utilizes GitHub Discussions instead. It has support for replies and other cool stuff from GitHub Discussions. The big advantage is the fact that it uses your repository's Discussions, which is more suitable for comments. I would really appreciate it if you tried it. Feedback is welcome, the code is [open source](https://github.com/laymonage/giscus).

You can convert existing issues into discussions, as described [here](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion). 

Thanks!

**Comment by bjcarlson42** [comment]
Looks like a cool project. I am currently in the process of switching my site from chakra-ui to styled components but after I finish that I'll look into giscus.
