### ISSUE TITLE
Incorrect view or like count?

### ISSUE THREAD

**Issue by farhan2077** [bjcarlson42/benjamincarlson.io#32]
The blog [https://www.benjamincarlson.io/blog/using-react-useeffect](https://www.benjamincarlson.io/blog/using-react-useeffect) in your website has more `likes` than `views`. Is this a possible bug or am I missing something? I have attached a screenshot below.
![image](https://user-images.githubusercontent.com/32035481/127738474-0a71b716-962d-4a5b-9973-c2417ed67781.png)

**Comment by bjcarlson42** [comment]
Thanks for bringing this up. I manually fixed the issue by resetting the likes. It looks like this is a bug. The user can manually type in the url (with the api) and increment the likes over and over. Anyone is welcome to create a pr and try to fix this. I don't have time at the moment but I'll definitely look more into this.
